<?php

namespace Workbench\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChannelListerFieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Explicitly use sqlite connection to populate the file that the server will use
        DB::connection('sqlite')->table('channel_lister_fields')->insert($this->data());
    }

    protected function data(): array
    {
        $now = now()->format('Y-m-d H:i:s');

        return [
            [
                'ordering' => 1,
                'field_name' => 'Auction Title',
                'display_name' => 'Title',
                'tooltip' => 'Titles should be easy to read and keyword rich 80 Character max<br><b>No special characters</b><br>This title is also the eBay title',
                'example' => 'Licensed Mercedes Benz SL-65 12V Kids Battery Powered Ride On Car - Red',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[^®^™*_]{10,80}$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 2,
                'field_name' => 'Inventory Number',
                'display_name' => 'SKU',
                'tooltip' => 'Stock Keeping Unit should uniquely identify a product',
                'example' => 'SON-KEVLARCORD-50FT-ORNG-BSPC080',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => null,
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 3,
                'field_name' => 'Labels',
                'display_name' => 'Channel Advisor Labels',
                'tooltip' => null,
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 4,
                'field_name' => 'Brand',
                'display_name' => '',
                'tooltip' => 'Brand name as we want it to appear on listings',
                'example' => 'ASR Outdoor',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'ASR Federal||ASR Outdoor||ASR Tactical||Kidplokio||Brandon Dallas||Creative Covers||Disney||Disney Co.||EverTek||Fisher Price||Flatline Ops||Garret||Gear Aid||Heininger||Hitchmate||Hornungs||KidPlay Products||Kipsun Destination Lifestyle||Mattel||McNett||Mitsuba||Nickelodeon||Peppa Pig||PJ Masks||Think Tank Technology||Universal||Universal Hobby||Universal Outdoor||Universal Tool||Zak Tool||__OTHER__',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 5,
                'field_name' => 'MPN',
                'display_name' => 'Model Number',
                'tooltip' => 'Model must be different for every listing',
                'example' => '12ACPBS',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 6,
                'field_name' => 'UPC',
                'display_name' => 'UPC or EAN Override',
                'tooltip' => '',
                'example' => '60886081975',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '^[0-9]{12,13}$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 7,
                'field_name' => 'SKU Type',
                'display_name' => '',
                'tooltip' => '',
                'example' => 'Standard',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'standard||bundle||child||parent',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 8,
                'field_name' => 'Bundle Components',
                'display_name' => 'Bundle Components',
                'tooltip' => 'This field can be used to create bundle products.',
                'example' => 'sku1=1,sku2=7',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '^([A-Z\\-0-9]{5,40})=\\d+(,([A-Z\\-0-9]{5,40})=\\d+)*$',
                'required' => 0,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 9,
                'field_name' => 'Vary By',
                'display_name' => 'Vary By',
                'tooltip' => 'Comma separated list of each field to vary by.',
                'example' => 'Color,Size',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 10,
                'field_name' => 'Parent SKU',
                'display_name' => 'Parent SKU',
                'tooltip' => 'SKU of the Parent',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[A-Z\\-0-9]{5,40}$|^Parent$',
                'required' => 0,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 11,
                'field_name' => 'Seller Cost',
                'display_name' => 'Cost',
                'tooltip' => '',
                'example' => '6.72',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 12,
                'field_name' => 'Buy It Now Price',
                'display_name' => 'List Price',
                'tooltip' => '',
                'example' => '24.99',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 13,
                'field_name' => 'Retail Price',
                'display_name' => 'MSRP',
                'tooltip' => 'MSRP must be greater than Price',
                'example' => '39.99',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 14,
                'field_name' => 'Sector',
                'display_name' => 'Sector',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'Automotive & Garage Accessories||Badges, Wallets, & Accessories||Camping, Hiking, & Outdoor Gear Repair||Clothing||Craft, Jeweler, & Hobby Tools||Electronics & Gadget Accessories||Fishing||Gold Panning||Handcuff Keys & Escape Tools||Health & Personal Care||Home, Kitchen, & Garden||Hunting & Gun Accessories||Knives, Blades, & Personal Security||Prank, Spy, & Novelty||Safety, Survival, & Emergency||School & Office Supplies||Scuba & Dive Gear Accessories||Sports & Fitness||Toys & Games||Travel||Misc||',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 15,
                'field_name' => 'Country of Manufacture',
                'display_name' => 'Country Of Origin',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'China==China||United States==United States||Italy==Italy||Afghanistan==Afghanistan||Albania==Albania||Algeria==Algeria||American Samoa==American Samoa||Andorra==Andorra||Angola==Angola||Anguilla==Anguilla||Antarctica==Antarctica||Antigua and Barbuda==Antigua and Barbuda||Argentina==Argentina||Armenia==Armenia||Aruba==Aruba||Australia==Australia||Austria==Austria||Azerbaijan==Azerbaijan||Bahamas==Bahamas||Bahrain==Bahrain||Bangladesh==Bangladesh||Barbados==Barbados||Belarus==Belarus||Belgium==Belgium||Belize==Belize||Benin==Benin||Bermuda==Bermuda||Bhutan==Bhutan||Bolivia==Bolivia||Bonaire==Bonaire||Bosnia and Herzegovina==Bosnia and Herzegovina||Botswana==Botswana||Bouvet Island==Bouvet Island||Brazil==Brazil||British Indian Ocean Territory==British Indian Ocean Territory||Brunei Darussalam==Brunei Darussalam||Bulgaria==Bulgaria||Burkina Faso==Burkina Faso||Burundi==Burundi||Cambodia==Cambodia||Cameroon==Cameroon||Canada==Canada||Cape Verde==Cape Verde||Cayman Islands==Cayman Islands||Central African Republic==Central African Republic||Chad==Chad||Chile==Chile||Christmas Island==Christmas Island||Cocos Islands==Cocos (Keeling) Islands||Colombia==Colombia||Comoros==Comoros||Congo==Congo||Democratic Republic of the Congo==Democratic Republic of the Congo||Cook Islands==Cook Islands||Costa Rica==Costa Rica||Croatia==Croatia||Cuba==Cuba||Curacao==Curacao||Cyprus==Cyprus||Czech Republic==Czech Republic||Cote d\'Ivoire==Cote d\'Ivoire||Denmark==Denmark||Djibouti==Djibouti||Dominica==Dominica||Dominican Republic==Dominican Republic||Ecuador==Ecuador||Egypt==Egypt||El Salvador==El Salvador||Equatorial Guinea==Equatorial Guinea||Eritrea==Eritrea||Estonia==Estonia||Ethiopia==Ethiopia||Falkland Islands==Falkland Islands (Malvinas)||Faroe Islands==Faroe Islands||Fiji==Fiji||Finland==Finland||France==France||French Guiana==French Guiana||French Polynesia==French Polynesia||French Southern Territories==French Southern Territories||Gabon==Gabon||Gambia==Gambia||Georgia==Georgia||Germany==Germany||Ghana==Ghana||Gibraltar==Gibraltar||Greece==Greece||Greenland==Greenland||Grenada==Grenada||Guadeloupe==Guadeloupe||Guam==Guam||Guatemala==Guatemala||Guernsey==Guernsey||Guinea==Guinea||Guinea-Bissau==Guinea-Bissau||Guyana==Guyana||Haiti==Haiti||Heard Island and McDonald Mcdonald Islands==Heard Island and McDonald Mcdonald Islands||Holy See==Holy See (Vatican City State)||Honduras==Honduras||Hong Kong==Hong Kong||Hungary==Hungary||Iceland==Iceland||India==India||Indonesia==Indonesia||Islamic Republic of Iran==Iran, Islamic Republic of||Iraq==Iraq||Ireland==Ireland||Isle of Man==Isle of Man||Israel==Israel||Jamaica==Jamaica||Japan==Japan||Jersey==Jersey||Jordan==Jordan||Kazakhstan==Kazakhstan||Kenya==Kenya||Kiribati==Kiribati||Democratic People\'s Republic of Korea==Korea, Democratic People\'s Republic of||Republic of Korea==Korea, Republic of||Kuwait==Kuwait||Kyrgyzstan==Kyrgyzstan||Lao People\'s Democratic Republic==Lao People\'s Democratic Republic||Latvia==Latvia||Lebanon==Lebanon||Lesotho==Lesotho||Liberia==Liberia||Libya==Libya||Liechtenstein==Liechtenstein||Lithuania==Lithuania||Luxembourg==Luxembourg||Macao==Macao||the Former Yugoslav Republic of Macedonia==Macedonia, the Former Yugoslav Republic of||Madagascar==Madagascar||Malawi==Malawi||Malaysia==Malaysia||Maldives==Maldives||Mali==Mali||Malta==Malta||Marshall Islands==Marshall Islands||Martinique==Martinique||Mauritania==Mauritania||Mauritius==Mauritius||Mayotte==Mayotte||Mexico==Mexico||Federated States of Micronesia==Micronesia, Federated States of||Republic of Moldova==Moldova, Republic of||Monaco==Monaco||Mongolia==Mongolia||Montenegro==Montenegro||Montserrat==Montserrat||Morocco==Morocco||Mozambique==Mozambique||Myanmar==Myanmar||Namibia==Namibia||Nauru==Nauru||Nepal==Nepal||Netherlands==Netherlands||New Caledonia==New Caledonia||New Zealand==New Zealand||Nicaragua==Nicaragua||Niger==Niger||Nigeria==Nigeria||Niue==Niue||Norfolk Island==Norfolk Island||Northern Mariana Islands==Northern Mariana Islands||Norway==Norway||Oman==Oman||Pakistan==Pakistan||Palau==Palau||State of Palestine==Palestine, State of||Panama==Panama||Papua New Guinea==Papua New Guinea||Paraguay==Paraguay||Peru==Peru||Philippines==Philippines||Pitcairn==Pitcairn||Poland==Poland||Portugal==Portugal||Puerto Rico==Puerto Rico||Qatar==Qatar||Romania==Romania||Russian Federation==Russian Federation||Rwanda==Rwanda||Reunion==Reunion||Saint Barthelemy==Saint Barthelemy||Saint Helena==Saint Helena||Saint Kitts and Nevis==Saint Kitts and Nevis||Saint Lucia==Saint Lucia||Saint Martin==Saint Martin (French part)||Saint Pierre and Miquelon==Saint Pierre and Miquelon||Saint Vincent and the Grenadines==Saint Vincent and the Grenadines||Samoa==Samoa||San Marino==San Marino||Sao Tome and Principe==Sao Tome and Principe||Saudi Arabia==Saudi Arabia||Senegal==Senegal||Serbia==Serbia||Seychelles==Seychelles||Sierra Leone==Sierra Leone||Singapore==Singapore||Sint Maarten==Sint Maarten (Dutch part)||Slovakia==Slovakia||Slovenia==Slovenia||Solomon Islands==Solomon Islands||Somalia==Somalia||South Africa==South Africa||South Georgia and the South Sandwich Islands==South Georgia and the South Sandwich Islands||South Sudan==South Sudan||Spain==Spain||Sri Lanka==Sri Lanka||Sudan==Sudan||Suriname==Suriname||Svalbard and Jan Mayen==Svalbard and Jan Mayen||Swaziland==Swaziland||Sweden==Sweden||Switzerland==Switzerland||Syrian Arab Republic==Syrian Arab Republic||Taiwan==Taiwan, Province of China||Tajikistan==Tajikistan||United Republic of Tanzania==United Republic of Tanzania||Thailand==Thailand||Timor-Leste==Timor-Leste||Togo==Togo||Tokelau==Tokelau||Tonga==Tonga||Trinidad and Tobago==Trinidad and Tobago||Tunisia==Tunisia||Turkey==Turkey||Turkmenistan==Turkmenistan||Turks and Caicos Islands==Turks and Caicos Islands||Tuvalu==Tuvalu||Uganda==Uganda||Ukraine==Ukraine||United Arab Emirates==United Arab Emirates||United Kingdom==United Kingdom||United States Minor Outlying Islands==United States Minor Outlying Islands||Uruguay==Uruguay||Uzbekistan==Uzbekistan||Vanuatu==Vanuatu||Venezuela==Venezuela||Viet Nam==Viet Nam||British Virgin Islands==British Virgin Islands||US Virgin Islands==US Virgin Islands||Wallis and Futuna==Wallis and Futuna||Western Sahara==Western Sahara||Yemen==Yemen||Zambia==Zambia||Zimbabwe==Zimbabwe',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 16,
                'field_name' => 'Color',
                'display_name' => '',
                'tooltip' => '',
                'example' => 'Dark Green',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 17,
                'field_name' => 'Size',
                'display_name' => '',
                'tooltip' => '',
                'example' => 'Medium',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 18,
                'field_name' => 'Material',
                'display_name' => '',
                'tooltip' => 'The main or most notable material',
                'example' => 'Polyester',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 19,
                'field_name' => 'Weight',
                'display_name' => 'Product Weight (lbs)',
                'tooltip' => 'The weight of the product itself, without its product packaging.',
                'example' => '0.98',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 20,
                'field_name' => 'Height',
                'display_name' => 'Product Height (in)',
                'tooltip' => 'The height of the product itself, without its product packaging.',
                'example' => '3.25',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 21,
                'field_name' => 'Length',
                'display_name' => 'Product Length (in)',
                'tooltip' => 'The length of the product itself, without its product packaging.',
                'example' => '10',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 22,
                'field_name' => 'Width',
                'display_name' => 'Product Width (in)',
                'tooltip' => 'The width of the product itself, without its product packaging.',
                'example' => '3.5',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 23,
                'field_name' => 'Cost Shipping',
                'display_name' => 'Calculated Shipping Cost',
                'tooltip' => 'Algorithmically Determined from Ship Dimensions, Ship Packaging and Hazmat',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 24,
                'field_name' => 'Total Quantity',
                'display_name' => 'Local Quantity',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'integer',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 25,
                'field_name' => 'Short Description',
                'display_name' => '',
                'tooltip' => '2-3 sentences, no HTML, also used for TL;DR. Answer "Why do I care?" and "What will this do for me?"',
                'example' => 'Never more will you have to fear the biting, stinging swarms when enjoying the great outdoors! This mosquito net is perfect for a family camping trip or a fishing trip.',
                'marketplace' => 'common',
                'input_type' => 'textarea',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 26,
                'field_name' => 'Description',
                'display_name' => 'Full Description',
                'tooltip' => 'No need to use <code>&lt;p&gt;</code> or <code>&lt;br&gt;</code> tags in the Description',
                'example' => 'This mosquito net is great for any group outing, or if you just want to make sure you have bug defense at the ready. Keep one with your garden tools, in your tackle box, with picnicking supplies, and in your hiking backpack! Its strong netting ensures defense against annoying mosquitoes.

Camo fabric and an elastic neck closure make this set great for all occasions. The lightweight construction and camouflage fabric make this a versatile head net ideal for keeping those pesky bugs away from your face.',
                'marketplace' => 'common',
                'input_type' => 'textarea',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 27,
                'field_name' => 'amazon_product_type',
                'display_name' => 'Amazon Product Type',
                'tooltip' => 'Amazon-specific product classification that determines which attributes are required for listing on Amazon',
                'example' => 'TOYS_AND_GAMES',
                'marketplace' => 'amazon',
                'input_type' => 'custom',
                'input_type_aux' => 'amazon-product-type-search',
                'required' => 0,
                'grouping' => 'Amazon Specific',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
