<?php

namespace Workbench\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChannelListerFieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Explicitly use sqlite connection to populate the file that the server will use
        DB::connection('sqlite')->table('channel_lister_fields')->insert($this->data());
        // }
    }

    protected function data(): array
    {
        $now = now()->format('Y-m-d H:i:s');

        return [
            [
                'ordering' => 1,
                'field_name' => 'Auction Title',
                'display_name' => 'Title',
                'tooltip' => 'Titles should be easy to read and keyword rich 80 Character max<br><b>No special characters</b><br>This title is also the eBay title',
                'example' => 'Licensed Mercedes Benz SL-65 12V Kids Battery Powered Ride On Car - Red',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[^®^™*_]{10,80}$',
                'required' => 1,
                'grouping' => 'Titles and Media',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 4,
                'field_name' => 'Inventory Number',
                'display_name' => 'SKU',
                'tooltip' => 'Stock Keeping Unit should uniquely identify a product',
                'example' => 'SON-KEVLARCORD-50FT-ORNG-BSPC080',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => null,
                'required' => 1,
                'grouping' => 'Titles and Media',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 6,
                'field_name' => 'Labels',
                'display_name' => 'Channel Advisor Labels',
                'tooltip' => null,
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Titles and Media',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 7,
                'field_name' => 'image1',
                'display_name' => 'Main Image Url',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 1,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 8,
                'field_name' => 'image1_alt',
                'display_name' => 'Main Image Desciption',
                'tooltip' => '',
                'example' => 'Mosquito head net in use',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 9,
                'field_name' => 'image2',
                'display_name' => 'Image Detail 1',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 10,
                'field_name' => 'image2_alt',
                'display_name' => 'Image Detail 1 Description',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 11,
                'field_name' => 'image3',
                'display_name' => 'Image Detail 2',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 12,
                'field_name' => 'image3_alt',
                'display_name' => 'Image Detail 2 Description',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 13,
                'field_name' => 'image4',
                'display_name' => 'Image Detail 3',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 14,
                'field_name' => 'image4_alt',
                'display_name' => 'Image Detail 3 Description',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 15,
                'field_name' => 'image5',
                'display_name' => 'Image Detail 4',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 16,
                'field_name' => 'image5_alt',
                'display_name' => 'Image Detail 4 Description',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 17,
                'field_name' => 'image6',
                'display_name' => 'Image Detail 5',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 18,
                'field_name' => 'image6_alt',
                'display_name' => 'Image Detail 5 Description',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 33,
                'field_name' => 'video1',
                'display_name' => 'Main Video URL',
                'tooltip' => '',
                'example' => 'https://picsum.photos/200',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 34,
                'field_name' => 'video1_alt',
                'display_name' => 'Main Video Description',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Titles and Media',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 35,
                'field_name' => 'google_product_category',
                'display_name' => 'Google Category',
                'tooltip' => '<p class="form-text">
        Search <a href="https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt" target="_blank">Google Categories</a>. <a href="https://support.google.com/merchants/answer/1705911?hl=en" target="_blank">Google Taxonomy Documentation</a>.<br>Use either the number OR the text, not both.
</p>',
                'example' => 'Sporting Goods > Outdoor Recreation > Camping & Hiking > Mosquito Nets & Insect Screens',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[0-9]+$|^[a-zA-Z> &]+$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 36,
                'field_name' => 'Brand',
                'display_name' => '',
                'tooltip' => 'Brand name as we want it to appear on listings',
                'example' => 'ASR Outdoor',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'ASR Federal||ASR Outdoor||ASR Tactical||Kidplokio||Brandon Dallas||Creative Covers||Disney||Disney Co.||EverTek||Fisher Price||Flatline Ops||Garret||Gear Aid||Heininger||Hitchmate||Hornungs||KidPlay Products||Kipsun Destination Lifestyle||Mattel||McNett||Mitsuba||Nickelodeon||Peppa Pig||PJ Masks||Think Tank Technology||Universal||Universal Hobby||Universal Outdoor||Universal Tool||Zak Tool||__OTHER__',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 37,
                'field_name' => 'MPN',
                'display_name' => 'Model Number',
                'tooltip' => 'Model must be different for every listing',
                'example' => '12ACPBS',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 39,
                'field_name' => 'UPC',
                'display_name' => 'UPC or EAN Override',
                'tooltip' => '',
                'example' => '60886081975',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '^[0-9]{12,13}$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 40,
                'field_name' => 'SKU Type',
                'display_name' => '',
                'tooltip' => '',
                'example' => 'Standard',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'standard||bundle||child||parent',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 41,
                'field_name' => 'Bundle Components',
                'display_name' => 'Bundle Components',
                'tooltip' => 'This field can be used to create bundle products.',
                'example' => 'sku1=1,sku2=7',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '^([A-Z\\-0-9]{5,40})=\\d+(,([A-Z\\-0-9]{5,40})=\\d+)*$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 42,
                'field_name' => 'Vary By',
                'display_name' => 'Vary By',
                'tooltip' => 'Comma separated list of each field to vary by.',
                'example' => 'Color,Size',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 43,
                'field_name' => 'Parent SKU',
                'display_name' => 'Parent SKU',
                'tooltip' => 'SKU of the Parent',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[A-Z\\-0-9]{5,40}$|^Parent$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 44,
                'field_name' => 'Seller Cost',
                'display_name' => 'Cost',
                'tooltip' => '',
                'example' => '6.72',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 45,
                'field_name' => 'Buy It Now Price',
                'display_name' => 'List Price',
                'tooltip' => '',
                'example' => '24.99',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 46,
                'field_name' => 'min_price_override',
                'display_name' => 'Minimum Price Override',
                'tooltip' => 'Overrides the calculated minimum price',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 47,
                'field_name' => 'Retail Price',
                'display_name' => 'MSRP',
                'tooltip' => 'MSRP must be greater than Price',
                'example' => '39.99',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 48,
                'field_name' => 'MAP_price',
                'display_name' => 'MAP Price',
                'tooltip' => 'MInimum Advertised Price<br>Lowest amount we can list the product',
                'example' => '19.99',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 49,
                'field_name' => 'Sector',
                'display_name' => 'Sector',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'Automotive & Garage Accessories||Badges, Wallets, & Accessories||Camping, Hiking, & Outdoor Gear Repair||Clothing||Craft, Jeweler, & Hobby Tools||Electronics & Gadget Accessories||Fishing||Gold Panning||Handcuff Keys & Escape Tools||Health & Personal Care||Home, Kitchen, & Garden||Hunting & Gun Accessories||Knives, Blades, & Personal Security||Prank, Spy, & Novelty||Safety, Survival, & Emergency||School & Office Supplies||Scuba & Dive Gear Accessories||Sports & Fitness||Toys & Games||Travel||Misc||',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 50,
                'field_name' => 'Country of Manufacture',
                'display_name' => 'Country Of Origin',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'China==China||United States==United States||Italy==Italy||Afghanistan==Afghanistan||Albania==Albania||Algeria==Algeria||American Samoa==American Samoa||Andorra==Andorra||Angola==Angola||Anguilla==Anguilla||Antarctica==Antarctica||Antigua and Barbuda==Antigua and Barbuda||Argentina==Argentina||Armenia==Armenia||Aruba==Aruba||Australia==Australia||Austria==Austria||Azerbaijan==Azerbaijan||Bahamas==Bahamas||Bahrain==Bahrain||Bangladesh==Bangladesh||Barbados==Barbados||Belarus==Belarus||Belgium==Belgium||Belize==Belize||Benin==Benin||Bermuda==Bermuda||Bhutan==Bhutan||Bolivia==Bolivia||Bonaire==Bonaire||Bosnia and Herzegovina==Bosnia and Herzegovina||Botswana==Botswana||Bouvet Island==Bouvet Island||Brazil==Brazil||British Indian Ocean Territory==British Indian Ocean Territory||Brunei Darussalam==Brunei Darussalam||Bulgaria==Bulgaria||Burkina Faso==Burkina Faso||Burundi==Burundi||Cambodia==Cambodia||Cameroon==Cameroon||Canada==Canada||Cape Verde==Cape Verde||Cayman Islands==Cayman Islands||Central African Republic==Central African Republic||Chad==Chad||Chile==Chile||Christmas Island==Christmas Island||Cocos Islands==Cocos (Keeling) Islands||Colombia==Colombia||Comoros==Comoros||Congo==Congo||Democratic Republic of the Congo==Democratic Republic of the Congo||Cook Islands==Cook Islands||Costa Rica==Costa Rica||Croatia==Croatia||Cuba==Cuba||Curacao==Curacao||Cyprus==Cyprus||Czech Republic==Czech Republic||Cote d\'Ivoire==Cote d\'Ivoire||Denmark==Denmark||Djibouti==Djibouti||Dominica==Dominica||Dominican Republic==Dominican Republic||Ecuador==Ecuador||Egypt==Egypt||El Salvador==El Salvador||Equatorial Guinea==Equatorial Guinea||Eritrea==Eritrea||Estonia==Estonia||Ethiopia==Ethiopia||Falkland Islands==Falkland Islands (Malvinas)||Faroe Islands==Faroe Islands||Fiji==Fiji||Finland==Finland||France==France||French Guiana==French Guiana||French Polynesia==French Polynesia||French Southern Territories==French Southern Territories||Gabon==Gabon||Gambia==Gambia||Georgia==Georgia||Germany==Germany||Ghana==Ghana||Gibraltar==Gibraltar||Greece==Greece||Greenland==Greenland||Grenada==Grenada||Guadeloupe==Guadeloupe||Guam==Guam||Guatemala==Guatemala||Guernsey==Guernsey||Guinea==Guinea||Guinea-Bissau==Guinea-Bissau||Guyana==Guyana||Haiti==Haiti||Heard Island and McDonald Mcdonald Islands==Heard Island and McDonald Mcdonald Islands||Holy See==Holy See (Vatican City State)||Honduras==Honduras||Hong Kong==Hong Kong||Hungary==Hungary||Iceland==Iceland||India==India||Indonesia==Indonesia||Islamic Republic of Iran==Iran, Islamic Republic of||Iraq==Iraq||Ireland==Ireland||Isle of Man==Isle of Man||Israel==Israel||Jamaica==Jamaica||Japan==Japan||Jersey==Jersey||Jordan==Jordan||Kazakhstan==Kazakhstan||Kenya==Kenya||Kiribati==Kiribati||Democratic People\'s Republic of Korea==Korea, Democratic People\'s Republic of||Republic of Korea==Korea, Republic of||Kuwait==Kuwait||Kyrgyzstan==Kyrgyzstan||Lao People\'s Democratic Republic==Lao People\'s Democratic Republic||Latvia==Latvia||Lebanon==Lebanon||Lesotho==Lesotho||Liberia==Liberia||Libya==Libya||Liechtenstein==Liechtenstein||Lithuania==Lithuania||Luxembourg==Luxembourg||Macao==Macao||the Former Yugoslav Republic of Macedonia==Macedonia, the Former Yugoslav Republic of||Madagascar==Madagascar||Malawi==Malawi||Malaysia==Malaysia||Maldives==Maldives||Mali==Mali||Malta==Malta||Marshall Islands==Marshall Islands||Martinique==Martinique||Mauritania==Mauritania||Mauritius==Mauritius||Mayotte==Mayotte||Mexico==Mexico||Federated States of Micronesia==Micronesia, Federated States of||Republic of Moldova==Moldova, Republic of||Monaco==Monaco||Mongolia==Mongolia||Montenegro==Montenegro||Montserrat==Montserrat||Morocco==Morocco||Mozambique==Mozambique||Myanmar==Myanmar||Namibia==Namibia||Nauru==Nauru||Nepal==Nepal||Netherlands==Netherlands||New Caledonia==New Caledonia||New Zealand==New Zealand||Nicaragua==Nicaragua||Niger==Niger||Nigeria==Nigeria||Niue==Niue||Norfolk Island==Norfolk Island||Northern Mariana Islands==Northern Mariana Islands||Norway==Norway||Oman==Oman||Pakistan==Pakistan||Palau==Palau||State of Palestine==Palestine, State of||Panama==Panama||Papua New Guinea==Papua New Guinea||Paraguay==Paraguay||Peru==Peru||Philippines==Philippines||Pitcairn==Pitcairn||Poland==Poland||Portugal==Portugal||Puerto Rico==Puerto Rico||Qatar==Qatar||Romania==Romania||Russian Federation==Russian Federation||Rwanda==Rwanda||Reunion==Reunion||Saint Barthelemy==Saint Barthelemy||Saint Helena==Saint Helena||Saint Kitts and Nevis==Saint Kitts and Nevis||Saint Lucia==Saint Lucia||Saint Martin==Saint Martin (French part)||Saint Pierre and Miquelon==Saint Pierre and Miquelon||Saint Vincent and the Grenadines==Saint Vincent and the Grenadines||Samoa==Samoa||San Marino==San Marino||Sao Tome and Principe==Sao Tome and Principe||Saudi Arabia==Saudi Arabia||Senegal==Senegal||Serbia==Serbia||Seychelles==Seychelles||Sierra Leone==Sierra Leone||Singapore==Singapore||Sint Maarten==Sint Maarten (Dutch part)||Slovakia==Slovakia||Slovenia==Slovenia||Solomon Islands==Solomon Islands||Somalia==Somalia||South Africa==South Africa||South Georgia and the South Sandwich Islands==South Georgia and the South Sandwich Islands||South Sudan==South Sudan||Spain==Spain||Sri Lanka==Sri Lanka||Sudan==Sudan||Suriname==Suriname||Svalbard and Jan Mayen==Svalbard and Jan Mayen||Swaziland==Swaziland||Sweden==Sweden||Switzerland==Switzerland||Syrian Arab Republic==Syrian Arab Republic||Taiwan==Taiwan, Province of China||Tajikistan==Tajikistan||United Republic of Tanzania==United Republic of Tanzania||Thailand==Thailand||Timor-Leste==Timor-Leste||Togo==Togo||Tokelau==Tokelau||Tonga==Tonga||Trinidad and Tobago==Trinidad and Tobago||Tunisia==Tunisia||Turkey==Turkey||Turkmenistan==Turkmenistan||Turks and Caicos Islands==Turks and Caicos Islands||Tuvalu==Tuvalu||Uganda==Uganda||Ukraine==Ukraine||United Arab Emirates==United Arab Emirates||United Kingdom==United Kingdom||United States Minor Outlying Islands==United States Minor Outlying Islands||Uruguay==Uruguay||Uzbekistan==Uzbekistan||Vanuatu==Vanuatu||Venezuela==Venezuela||Viet Nam==Viet Nam||British Virgin Islands==British Virgin Islands||US Virgin Islands==US Virgin Islands||Wallis and Futuna==Wallis and Futuna||Western Sahara==Western Sahara||Yemen==Yemen||Zambia==Zambia||Zimbabwe==Zimbabwe',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 51,
                'field_name' => 'country_of_origin_2_digit',
                'display_name' => 'Country of Origin 2 Digit',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[A-Z]{2}$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 52,
                'field_name' => 'country_of_origin_3_digit',
                'display_name' => 'Country of Origin 3 Digit',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '^[A-Z]{3}$',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 53,
                'field_name' => 'Color',
                'display_name' => '',
                'tooltip' => '',
                'example' => 'Dark Green',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 54,
                'field_name' => 'Size',
                'display_name' => '',
                'tooltip' => '',
                'example' => 'Medium',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 55,
                'field_name' => 'Material',
                'display_name' => '',
                'tooltip' => 'The main or most notable material',
                'example' => 'Polyester',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 56,
                'field_name' => 'parts_per_item',
                'display_name' => 'Total Number of Pieces',
                'tooltip' => 'The sum of all the individual pieces from each product',
                'example' => '17',
                'marketplace' => 'common',
                'input_type' => 'integer',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 57,
                'field_name' => 'item_quantity',
                'display_name' => 'Packages per Listing',
                'tooltip' => 'The number of individual products in the listing<br>e.g. 3 for a bundle of 3 20pc sets',
                'example' => '3',
                'marketplace' => 'common',
                'input_type' => 'integer',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 58,
                'field_name' => 'Weight',
                'display_name' => 'Product Weight (lbs)',
                'tooltip' => 'The weight of the product itself, without its product packaging.',
                'example' => '0.98',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 59,
                'field_name' => 'Height',
                'display_name' => 'Product Height (in)',
                'tooltip' => 'The height of the product itself, without its product packaging.',
                'example' => '3.25',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 60,
                'field_name' => 'Length',
                'display_name' => 'Product Length (in)',
                'tooltip' => 'The length of the product itself, without its product packaging.',
                'example' => '10',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 61,
                'field_name' => 'Width',
                'display_name' => 'Product Width (in)',
                'tooltip' => 'The width of the product itself, without its product packaging.',
                'example' => '3.5',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 62,
                'field_name' => 'Total Quantity',
                'display_name' => 'Local Quantity',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'integer',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Details and Stats',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 63,
                'field_name' => 'ship_weight',
                'display_name' => 'Ship Weight (lbs)',
                'tooltip' => 'The weight of the product when packaged to ship. This is displayed on
the product page and used to calculate shipping costs for weight-based
shipping, if available.',
                'example' => '3.75',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 64,
                'field_name' => 'ship_length',
                'display_name' => 'Ship Length (in)',
                'tooltip' => 'Ship container length',
                'example' => '12',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 65,
                'field_name' => 'ship_width',
                'display_name' => 'Ship Width (in)',
                'tooltip' => 'Ship container width',
                'example' => '6',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 66,
                'field_name' => 'ship_height',
                'display_name' => 'Ship Height (in)',
                'tooltip' => 'Ship container height',
                'example' => '2',
                'marketplace' => 'common',
                'input_type' => 'decimal',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 67,
                'field_name' => 'hazmat',
                'display_name' => 'Hazmat',
                'tooltip' => 'Hazardous items need to ship via Ground',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'checkbox',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 68,
                'field_name' => 'ship_packaging',
                'display_name' => 'Packaging',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'select',
                'input_type_aux' => 'polymailer||expressenvelope||box||other',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 69,
                'field_name' => 'free_shipping',
                'display_name' => 'Free Shipping',
                'tooltip' => '',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'checkbox',
                'input_type_aux' => 'checked',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 70,
                'field_name' => 'cost_shipping',
                'display_name' => 'Calculated Shipping Cost',
                'tooltip' => 'Algorithmically Determined from Ship Dimensions, Ship Packaging and Hazmat',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 71,
                'field_name' => 'calculated_shipping_service',
                'display_name' => 'Calculated Shipping Service',
                'tooltip' => 'Algorithmically Determined from Ship Dimensions, Ship Packaging and Hazmat',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'custom',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 72,
                'field_name' => 'ship_cost_override',
                'display_name' => 'Ship Cost Override',
                'tooltip' => 'Optional, used to override calculated ship cost',
                'example' => '13.37',
                'marketplace' => 'common',
                'input_type' => 'currency',
                'input_type_aux' => '',
                'required' => 0,
                'grouping' => 'Shipping',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 74,
                'field_name' => 'Short Description',
                'display_name' => '',
                'tooltip' => '2-3 sentences, no HTML, also used for TL;DR. Answer "Why do I care?" and "What will this do for me?"',
                'example' => 'Never more will you have to fear the biting, stinging swarms when enjoying the great outdoors! This mosquito net is perfect for a family camping trip or a fishing trip.',
                'marketplace' => 'common',
                'input_type' => 'textarea',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 75,
                'field_name' => 'Description',
                'display_name' => 'Full Description',
                'tooltip' => 'No need to use <code>&lt;p&gt;</code> or <code>&lt;br&gt;</code> tags in the Description',
                'example' => 'This mosquito net is great for any group outing, or if you just want to make sure you have bug defense at the ready. Keep one with your garden tools, in your tackle box, with picnicking supplies, and in your hiking backpack! Its strong netting ensures defense against annoying mosquitoes.

Camo fabric and an elastic neck closure make this set great for all occasions. The lightweight construction and camouflage fabric make this a versatile head net ideal for keeping those pesky bugs away from your face.',
                'marketplace' => 'common',
                'input_type' => 'textarea',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'channeladvisor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 76,
                'field_name' => 'feature_1',
                'display_name' => 'Product Feature 1',
                'tooltip' => '',
                'example' => 'Durable and lightweight mosquito net',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 77,
                'field_name' => 'feature_2',
                'display_name' => 'Product Feature 2',
                'tooltip' => '',
                'example' => 'Compact size for easy storage and transport',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 78,
                'field_name' => 'feature_3',
                'display_name' => 'Product Feature 3',
                'tooltip' => '',
                'example' => 'Elastic neck closure for a secure fit',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 79,
                'field_name' => 'feature_4',
                'display_name' => 'Product Feature 4',
                'tooltip' => '',
                'example' => 'Camouflage pattern for outdoor use',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 80,
                'field_name' => 'feature_5',
                'display_name' => 'Product Feature 5',
                'tooltip' => '',
                'example' => 'Strong netting to keep bugs out',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Listing Description',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 81,
                'field_name' => 'customs_tariff_number',
                'display_name' => 'Customs Tariff Number',
                'tooltip' => '',
                'example' => '6307.90.9985',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 83,
                'field_name' => 'compliance_certifications',
                'display_name' => 'Compliance Certifications',
                'tooltip' => '',
                'example' => 'CE, RoHS',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 84,
                'field_name' => 'warranty',
                'display_name' => 'Warranty',
                'tooltip' => '',
                'example' => '2 years',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 85,
                'field_name' => 'return_policy',
                'display_name' => 'Return Policy',
                'tooltip' => '',
                'example' => '30 days',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 86,
                'field_name' => 'safety_warning',
                'display_name' => 'Safety Warning',
                'tooltip' => '',
                'example' => 'Keep away from fire',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 87,
                'field_name' => 'assembly_instructions',
                'display_name' => 'Assembly Instructions',
                'tooltip' => '',
                'example' => 'Easy to assemble, no tools required',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 88,
                'field_name' => 'care_instructions',
                'display_name' => 'Care Instructions',
                'tooltip' => '',
                'example' => 'Hand wash only',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 89,
                'field_name' => 'disclaimer',
                'display_name' => 'Disclaimer',
                'tooltip' => '',
                'example' => 'This is not a toy',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 90,
                'field_name' => 'prop65_warning',
                'display_name' => 'Prop 65 Warning',
                'tooltip' => '',
                'example' => 'Cancer and Reproductive Harm - www.P65Warnings.ca.gov',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 91,
                'field_name' => 'battery_warning',
                'display_name' => 'Battery Warning',
                'tooltip' => '',
                'example' => 'Keep batteries away from children',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 92,
                'field_name' => 'recycling_instructions',
                'display_name' => 'Recycling Instructions',
                'tooltip' => '',
                'example' => 'Recycle according to local regulations',
                'marketplace' => 'common',
                'input_type' => 'text',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 93,
                'field_name' => 'compliance_document',
                'display_name' => 'Compliance Document',
                'tooltip' => '',
                'example' => 'https://example.com/compliance.pdf',
                'marketplace' => 'common',
                'input_type' => 'url',
                'input_type_aux' => '^https://.+',
                'required' => 1,
                'grouping' => 'Compliance',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 108,
                'field_name' => 'contains_liquid',
                'display_name' => 'Contains Liquid Content',
                'tooltip' => 'Does the product contain liquid contents?',
                'example' => '',
                'marketplace' => 'common',
                'input_type' => 'checkbox',
                'input_type_aux' => '',
                'required' => 1,
                'grouping' => 'Other Fields',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ordering' => 17,
                'field_name' => 'amazon_product_type',
                'display_name' => 'Amazon Product Type',
                'tooltip' => 'Amazon-specific product classification that determines which attributes are required for listing on Amazon',
                'example' => 'TOYS_AND_GAMES',
                'marketplace' => 'amazon',
                'input_type' => 'custom',
                'input_type_aux' => 'amazon-product-type-search',
                'required' => 0,
                'grouping' => 'Amazon Specific',
                'type' => 'custom',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
